[program:render-port-proxy]
command=/usr/bin/socat TCP-LISTEN:%(ENV_PORT)s,fork,reuseaddr TCP:127.0.0.1:4444
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
priority=5

